version: "3.7"

services:
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
    networks:
      - recsys-network

  app:
    build:
      context: ./app
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - recsys-network

  bot:
    build:
      context: ./bot
    container_name: tg_bot
    command: python bot.py
    depends_on:
      - app
    networks:
      - recsys-network   

networks:
  recsys-network:
    name: recsys-network
    driver: bridge
    attachable: true
      
   


