version: "3.7"

services:
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
    networks:
      - recsys-network

  app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - recsys-network
      
networks:
  recsys-network:
    name: recsys-network
    driver: bridge
    attachable: true
